# Generated by Django 4.1.3 on 2023-01-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('nama', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('tipe', models.CharField(choices=[('ADMIN', 'ADMIN'), ('KASIR', 'KASIR')], default='ADMIN', max_length=5)),
                ('saldo_awal', models.PositiveIntegerField(default=0)),
                ('saldo_akhir', models.PositiveIntegerField(default=0)),
                ('total_penjualan', models.PositiveIntegerField(default=0)),
                ('total_void', models.PositiveIntegerField(default=0)),
                ('total_transfer', models.PositiveIntegerField(default=0)),
                ('total_pengeluaran', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]