# Generated by Django 4.1.3 on 2023-01-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EceranInvoice',
            fields=[
                ('nomor', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('tanggal', models.DateField(default=None)),
                ('jam', models.TimeField(default=None)),
                ('barang', models.JSONField(default=None)),
                ('total', models.PositiveIntegerField(default=None)),
                ('reset_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('tipe', models.CharField(choices=[('REGULAR', 'REGULAR'), ('VOID', 'VOID')], default='REGULAR', max_length=7)),
                ('catatan', models.CharField(blank=True, max_length=200, null=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.terminal')),
            ],
        ),
    ]