//AUTH STATE
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//ALERT STATE
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';

//SUPPLIER STATE
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_FAIL = 'ADD_SUPPLIER_FAIL';

export const GETTING_ALL_SUPPLIERS_NAME = 'GETTING_ALL_SUPPLIERS_NAME';
export const GET_ALL_SUPPLIERS_NAME_SUCCESS = 'GET_ALL_SUPPLIERS_NAME_SUCCESS';
export const GET_ALL_SUPPLIERS_NAME_FAIL = 'GET_ALL_SUPPLIERS_NAME_FAIL';

//PRODUCT STATE
export const ADD_PRODUCT_CATEGORY = 'ADD_PRODUCT_CATEGORY';
export const ADD_PRODUCT_CATEGORY_SUCCESS = 'ADD_PRODUCT_CATEGORY_SUCCESS';
export const ADD_PRODUCT_CATEGORY_FAIL = 'ADD_PRODUCT_CATEGORY_FAIL';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAILED';

export const GETTING_PRODUCT_CATEGORIES = 'GETTING_PRODUCT_CATEGORIES';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_FAIL = 'GET_PRODUCT_CATEGORIES_FAIL';
export const GETTING_ALL_PRODUCTS_CODE = 'GETTING_ALL_PRODUCTS_CODE';
export const GET_ALL_PRODUCTS_CODE_SUCCESS = 'GET_ALL_PRODUCTS_CODE_SUCCESS';
export const GET_ALL_PRODUCTS_CODE_FAIL = 'GET_ALL_PRODUCTS_CODE_FAIL';

export const GETTING_SPECIFIC_PRODUCT = 'GETTING_SPECIFIC_PRODUCT';
export const GET_SPECIFIC_PRODUCT_SUCCESS = 'GET_SPECIFIC_PRODUCT_SUCCESS';
export const GET_SPECIFIC_PRODUCT_FAIL = 'GET_SPECIFIC_PRODUCT_FAIL';

//ECERAN INVOICE STATE
export const CREATING_ECERAN_INVOICE = 'CREATING_ECERAN_INVOICE';
export const CREATE_ECERAN_INVOICE_SUCCESS = 'CREATE_ECERAN_INVOICE_SUCCESS';
export const CREATE_ECERAN_INVOICE_FAIL = 'CREATE_ECERAN_INVOICE_FAIL';
export const ECERAN_INVOICE_FINALISED = 'ECERAN_INVOICE_FINALISED';
export const GETTING_SPECIFIC_ECERAN_INVOICE = 'GET_SPECIFIC_ECERAN_INVOICE';
export const GET_SPECIFIC_ECERAN_INVOICE_SUCCESS = 'GET_SPECIFIC_ECERAN_INVOICE_SUCCESS';
export const GET_SPECIFIC_ECERAN_INVOICE_FAIL = 'GET_SPECIFIC_ECERAN_INVOICE_FAIL';

//TERMINAL STATE
export const GETTING_ALL_TERMINAL = 'GET_ALL_TERMINAL';
export const GET_ALL_TERMINAL_SUCCESS = 'GET_ALL_TERMINAL_SUCCESS';
export const GET_ALL_TERMINAL_FAILED = 'GET_ALL_TERMINAL_FAILED';
export const GET_SPECIFIC_TERMINAL = 'GET_SPECIFIC_TERMINAL';
export const GET_SPECIFIC_TERMINAL_SUCCESS  = 'GET_SPECIFIC_TERMINAL_SUCCESS';
export const GET_SPECIFIC_TERMINAL_FAILED = 'GET_SPECIFIC_TERMINAL_FAILED';
export const SET_TERMINAL = 'SET_TERMINAL';
export const GETTING_TERMINAL_SUMMARY = 'GETTING_TERMINAL_SUMMARY';
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESSFUL';
export const GET_SUMAMRY_FAILED = 'GET_SUMAMRY_FAILED';

//REPORT STATE
export const CREATING_REPORT = 'CREATING_REPORT';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS'
export const CREATE_REPORT_FAILED = 'CREATE_REPORT_FAILED'

