# Generated by Django 4.1.3 on 2023-01-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('nama', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('kode', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('modal', models.PositiveIntegerField(default=0)),
                ('pengangkutan', models.PositiveIntegerField(default=0)),
                ('harga_S', models.PositiveIntegerField(default=0)),
                ('harga_A', models.PositiveIntegerField(default=0)),
                ('harga_B', models.PositiveIntegerField(default=0)),
                ('stok', models.IntegerField(default=0)),
                ('po', models.PositiveIntegerField(default=0)),
                ('otw', models.PositiveIntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='product_pictures')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]