# Generated by Django 4.1.3 on 2023-01-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EceranDailyReport',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jam', models.TimeField()),
                ('tanggal', models.DateField()),
                ('saldo_awal', models.PositiveIntegerField()),
                ('total_regular', models.PositiveIntegerField()),
                ('total_void', models.PositiveIntegerField()),
                ('total_pengeluaran', models.PositiveIntegerField()),
                ('total_transfer', models.PositiveIntegerField()),
                ('penarikan', models.PositiveIntegerField()),
                ('saldo_akhir', models.PositiveIntegerField()),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.terminal')),
            ],
        ),
    ]