# Generated by Django 4.1.3 on 2023-01-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eceranDailyReport', '0001_initial'),
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=50)),
                ('catatan', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('total', models.PositiveIntegerField()),
                ('reset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eceranDailyReport.ecerandailyreport')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.terminal')),
            ],
        ),
    ]